server:
  port: 8762
spring:
  application:
     name: eureka-server
  security:
    user:
      name: admin
      password: 123456
eureka:
#  instance:
#    hostname: master
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    # 表示是否将自己注册到Eureka Server，默认为true。
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息，默认为true。
    fetch-registry: false
    healthcheck:
       enabled: true
    service-url:
        defaultZone: http://127.0.0.1:8762/eureka
  server:
    enable-self-preservation: false
